import Head from 'next/head'
import { gql } from '@apollo/client'

import client from './api/spacex-api'
import { Launch } from '../components/launch';

export default function Home({ launches }) {
  console.log(launches);
 
  return (
    <div className="container mx-auto">
      <Head>
        <title>SpaceX launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className="text-5xl font-black font-mono my-8">
          SpaceX launches
        </h1>
      </header>
      <main>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mb-12">
          {launches.map(launch => {
            return (
              <Launch key={launch.id} launch={launch} />
            )
          })}
          
        </div>
      </main>
    </div>
  )
}


export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    {
      launchesPast(limit: 20) {
        id
        mission_name
        launch_date_local
        launch_site {
          site_name_long
        }
        links {
          video_link
          flickr_images
        }
        rocket {
          rocket_name
        }
      }
    }
    `
  }) 

  return {
    props: {
      launches: data.launchesPast
    }
  }
}